from setuptools import setup, find_packages

with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

setup(
    name="cliv_gui",
    version="1.0.4",
    author="Night613",
    author_email="clivguicontact@gmail.com",
    description="Framework Python avançado para criação de menus GUI modernos e overlays transparentes sobre processos Windows. Inclui sistema de notificações, player de áudio, color picker HSV, e muito mais.",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/Night613/ClivGui",
    packages=find_packages(),
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Topic :: Software Development :: User Interfaces",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Games/Entertainment",
        "Topic :: System :: Monitoring",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
        "Operating System :: Microsoft :: Windows",
        "Environment :: Win32 (MS Windows)",
        "Natural Language :: Portuguese (Brazilian)",
        "Natural Language :: English",
    ],
    python_requires=">=3.7",
    install_requires=[
        "Pillow>=9.0.0",
        "pygame>=2.0.0",
        "keyboard>=0.13.5",
        "pywin32>=304",
        "psutil>=5.9.0",
        "pystray>=0.19.4",
    ],
    extras_require={
        "dev": [
            "pytest>=7.0.0",
            "black>=22.0.0",
            "flake8>=4.0.0",
            "mypy>=0.990",
        ],
    },
    keywords=[
        "gui",
        "menu",
        "overlay",
        "tkinter",
        "gaming",
        "esp",
        "aimbot",
        "trainer",
        "notifications",
        "toast",
        "modern-ui",
        "windows",
        "process-overlay",
        "audio-player",
        "color-picker",
        "dashboard",
        "system-tray",
        "hotkeys",
        "keybind",
        "slider",
        "checkbox",
        "graph",
        "realtime",
        "transparent",
        "borderless",
        "roblox-style",
        "discord-style",
    ],
    project_urls={
        "Bug Reports": "https://github.com/Night613/ClivGui/issues",
        "Source": "https://github.com/Night613/ClivGui",
        "Documentation": "https://github.com/Night613/ClivGui/blob/main/DOCS.md",
        "Examples": "https://github.com/Night613/ClivGui/tree/main/examples",
    },
    include_package_data=True,
    zip_safe=False,
    license="MIT",
    platforms=["Windows"],
)
